// app/components/Header.tsx
import Image from "next/image";

export default function Header() {
  return (
    <header className="w-full p-4">
      <nav className="max-w-7xl mx-auto">
        <p style={{ 
          fontFamily: 'var(--font-roboto), sans-serif',
          margin: 0,
          fontSize: '1.4rem',
          fontWeight: 700,
          color: '#424242'
        }}>Thomas Shouler</p>
      </nav>
      <div className="max-w-7xl mx-auto" style={{ overflow: 'visible', minHeight: '6px' }}>
        <Image 
          src="/double_line.png" 
          alt="Double line" 
          width={1200} 
          height={10}
          style={{ width: '100%', height: 'auto', transform: 'scaleY(0.6)', transformOrigin: 'top' }}
        />
      </div>
    </header>
  );
}

// src/components/Header.vue
<template>
  <div class="header">
    <a class="title">thomas shouler</a>
    <img class=single-line src="single_line.png">
    <a class="link">http://thomasshouler.io</a>
  </div>
</template>

<script>
  import '../assets/single_line.png';

  export default {
    name: 'ts-header',
  }
</script>

<style scoped lang="scss">
  @import '../main';

  div {
    margin: 2rem 0 0 0;
    height: 2.75rem;
    max-width: 40rem;
  }

  a.title {
    margin: 0;
    font-size: 1.4rem;
    font-weight: 700;
    color: $dark-gray;
  }

  img.single-line {
    width: 100%;
    height: 1px;
    position: relative;
    top: -0.75rem;
  }

  a.link {
    font-size: 0.85rem;
    font-weight: 100;
    color: $dark-gray;
    position: relative;
    top: -1rem;
  }
</style>
